title: Simon Dufour Blog
baseURL: /
params:
  cv:
    profile:
      enable: true
      name: 'Simon Dufour'
      tagline: 'Analyste-Programmeur Senior'
      avatar: 'simon-dufour.png'
    contact:
      enable: true
      location: 'Montréal, Canada'
      list:
        - icon: "fas fa-phone-square"
          url: "tel:5144669186"
          text: "514-466-9186"
        - icon: "fas fa-envelope-square"
          url: "mailto:sim.dufour@gmail.com"
          text: "sim.dufour@gmail.com"
        - icon: "fas fa-globe"
          url: "https://simondufour.dev"
          text: "simondufour.dev"
    summary:
      enable: true
      text: >-
        J'ai fait le développement d'une variété d'application de gestion. Je m'intéresse principalement au 
        développement d'application Angular et .NET. J'ai adoré travailler en Angular depuis ses tout débuts. C'est 
        une plateforme qui permet des solutions élégante à des problèmes complexes. Ce fût aussi mon introduction à la 
        philosophie de Redux et de la programmation réactive. Ce qui me passionne par-dessus tout, c'est de trouver des 
        façons innovatrice d'offrir à mes clients une application qui répond le mieux possible à leurs besoins en utilisant 
        tous les avantages que les nouvelles technologies nous offrent. J'ai une formation académique en gestion de projet, 
        en assurance qualité, en tests et en maintenance. Je n'hésite pas à utiliser dans la vie de tous les jours afin de 
        faire un travail de qualité et d'offrir à mes collègues une nouvelle perspective.
    
    experience:
      enable: true
      list:
        - title: "Développeur Front-end Senior"
          dates: "Nov 2019 - Aujourd'hui"
          company: "Desjardins"
          details: "Conception et implémentation d'applications en Angular en utilisant NgRx et RxJs."
          items: 
            - details: "Développement d'applications avec Angular 4-11."
            - details: "Gestion de l'état avec NgRx"
            - details: "Programmation réactive avec RxJs"
            - details: "Implémentation de Oauth2 et Auth0"
            - details: "Tests unitaires Jasmine"
            - details: "Support d'applications en production"
            - details: "SourceTree, Jira, Scrum, SonarQube"


  author: 'Simon Dufour'
  description: 'Développeur Senior, Angular, C#, Asp.NET'
  primaryColor: '#007599'
  textPrimaryColor: '#292929'

  contact:
    enable: true
    location: 'Montréal, Canada'
  palette: yellow
  header:
    type: header
    template: header
    title: Simon Dufour
    tagline: 'Father, Programmer, Gamer'
    logo_img: ''
    logo_img_alt: Fjord Logo
    background_img: /images/9.jpg
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
        icon_class: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: About
        url: /about
        style: link
        icon_class: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Style Guide
        url: /style-guide
        style: link
        icon_class: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Contact
        url: /contact
        style: link
        icon_class: ''
        new_window: false
        no_follow: false
      - label: CV
        url: '/cv'
        style: link
        icon_class: dev
        new_window: false
        no_follow: false
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/simdufour'
        style: icon
        icon_class: twitter
        new_window: true
        no_follow: false
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
        no_follow: false
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
        no_follow: false
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: linkedin
        new_window: true
        no_follow: false
      - type: action
        template: action
        label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: dev
        new_window: true
        no_follow: false
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=fjord&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    links: []
  domain: 'https://simon-dufour-blog-4e2c0.netlify.app'
  favicon: ''
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
